baseURL = "https://highlight-br.netlify.app"
disableLanguages = []
disqusShortname = ""
googleAnalytics = ""
languageCode = "pt-br"
languageName = "Pt"
paginate = "6"
summaryLength = "10"
theme = "twentytwenty"
title = "Highlight"

[markup.goldmark.renderer]
unsafe = true

[[menu.desktop]]
URL = "contact"
name = "Contato"
weight = 1

# [[menu.main]]
# URL = "/"
# name = "Home"
# weight = 1

[[menu.main]]
URL = "about"
name = "Sobre"
weight = 2

[[menu.main]]
URL = "blog"
name = "Blog"
weight = 3

[[menu.main]]
URL = "contact"
name = "Contato"
weight = 4

# [[menu.main]]
# URL = "sample-page"
# name = "Sample Page"
# weight = 5

[outputs]
home = ["HTML", "RSS", "JSON"]

[params]
author = "Hightlight Software"
description = "A Software Company"

[params.banner]
heading = "Venha nos conhecer!"
image = ""

[params.blog]
heading = "Descubra como software pode ajudar a sua empresa!"

[params.call_to_action]
button_label = "Fale Conosco!"
button_url = "contact"
content = "Oferecemos diversas soluções tecnológicas para o seu negócio."
enable = true
title = "Obtenha mais informações e aperfeiçoe sua empresa."

[params.footer]
address = "123 Main Street <br> Belo Horizonte - MG"
content = "Nós somos uma empresa fundada no polo tecnológico de Belo Horizonte."
copyright = "Copyright &copy; 2020 Highight Software"
hours = "Segunda à Sexta: 9:00AM–5:00PM <br> Fim de Semana e Feriados: 11:00AM–3:00PM"
title = "Sobre Nós"

[params.gallery]
enable = false

[[params.gallery.gallery_item]]
image = "images/2020-square-2.png"

[[params.gallery.gallery_item]]
image = "images/2020-square-1.png"

[params.social]
email = "#"
facebook = "#"
instagram = "#"
twitter = "#"
yelp = "#"

[taxonomies]
author = "author"
category = "categories"
tag = "tags"
