baseURL = "https://highlight-br.netlify.app"
disableLanguages = []
disqusShortname = ""
googleAnalytics = ""
languageCode = "pt-br"
languageName = "Pt"
paginate = "6"
summaryLength = "10"
theme = "twentytwenty"
title = "Highlight"
[markup.goldmark.renderer]
unsafe = true
[[menu.desktop]]
URL = "contact"
name = "Contato"
weight = 1
[[menu.main]]
URL = "about"
name = "Sobre"
weight = 2
[[menu.main]]
URL = "blog"
name = "Blog"
weight = 3
[[menu.main]]
URL = "contact"
name = "Contato"
weight = 4
[outputs]
home = ["HTML", "RSS", "JSON"]
[params]
author = "Hightlight Software"
description = "A Software Company"
[params.banner]
heading = ""
image = ""
[params.blog]
enable = false
heading = "Descubra como software pode ajudar a sua empresa!"
[params.call_to_action]
button_label = "Fale Conosco!"
button_url = "contact"
content = "Oferecemos diversas soluções tecnológicas para o seu negócio."
enable = true
title = "Obtenha mais informações e aperfeiçoe sua empresa."
[params.cards]
enable = true
[[params.cards.item]]
align = "left"
image = "images/websiteMaking.png"
text = "Uma loja para vender seus produtos ou serviços, um portfólio para mostrar seu trabalho, um blog para compartilhar suas idéias e muito mais!"
title = "Seu website!"
[[params.cards.item]]
align = "right"
image = "images/appMaking.png"
text = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."
title = "Seu aplicativo!"
[[params.cards.item]]
align = "left"
image = "images/softwareMaking.png"
text = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."
title = "Seu programa!"
[params.footer]
address = "Belo Horizonte - MG"
content = "Nós somos uma empresa fundada no polo tecnológico de Belo Horizonte."
copyright = "Copyright &copy; 2020 Highlight Software"
hours = "Segunda à Sexta: 9:00AM–5:00PM <br> Fim de Semana e Feriados: 11:00AM–3:00PM"
title = "Sobre Nós"
[params.gallery]
enable = false
[[params.gallery.gallery_item]]
image = "images/appMaking.png"
[[params.gallery.gallery_item]]
image = "images/websiteMaking.png"
[params.social]
email = "#"
facebook = "#"
instagram = "#"
twitter = "#"
yelp = "#"
[taxonomies]
author = "author"
category = "categories"
tag = "tags"
